### PR TITLE
Register modules to Curator (fix for ZEN)

### LINKED ISSUE #7: Integrate with Zeus Enhanced
[Original issue from ZEN](https://github.com/zen-mod/ZEN/issues/150#issue-487765041), moved here for better tracking.

### PR DESCRIPTION
**Pull request by zuedev**
resolves #7

### CODE REVIEW

**Comment by diwako** [comment]
Thanks, will take a look once I get some free time.

**Comment by diwako** [comment]
Just tried it out, also finally converted tabs to spaces...

The basic anomalies work, the remove anomaly module is missing (it was not there in default modules either so no biggy) and any module that needs a UI beforehand will not work. There are 2 possibilities that I am seeing now.

1. Create vanilla menus for these
2. Use ZENs functions for custom modules.

TBH creating new UIs would be the right thing as then no mod is needed for Zeus modules, but creating overlays in Arma is a pain. TBH ZEN custom modules are way more attractive from a time perspective.

**Comment by zeue** [comment]
Weird, it worked in vanilla during testing.

I could look into making the new UIs for you if you don't want to spend the time messing with them, as I think the Zeus modules shouldn't *depend* on ZEN to work.

**Comment by diwako** [comment]
The mods i tried with was CBA, ACE, ACEX and ACRE.

**Comment by TMZulu** [comment]
Any eta on this atm? For the initial fix for ZEN at least.

**Pull request closed without merging**
